import { useState } from "react";
import { Alert, StyleSheet, TextInput, View } from "react-native";
import { AppText, Button, colors, radius, spacing } from "@daycare/ui";
import { AppScreen } from "@/navigation/AppScreen";
import type { ServicePlanType, UnusedCreditPolicy } from "@daycare/core";
import { useCreateServicePlan, useInvoices, useMarkInvoicePaid, useServicePlans } from "@/booking/useBooking";
import { useI18n } from "@/i18n/I18nProvider";
import { servicePlanTypeKey } from "@/i18n/translations";

const planTypes: ServicePlanType[] = ["DAILY", "WEEKLY", "MONTHLY"];
export default function BillingAdminScreen() {
  const plans = useServicePlans(); const invoices = useInvoices(); const createPlan = useCreateServicePlan(); const markPaid = useMarkInvoicePaid();
  const { t, formatCurrency, formatDate } = useI18n();
  const [name, setName] = useState(""); const [price, setPrice] = useState(""); const [type, setType] = useState<ServicePlanType>("DAILY"); const [credits, setCredits] = useState("1"); const [policy, setPolicy] = useState<UnusedCreditPolicy>("EXPIRE");
  const submitPlan = async () => { const amount = Number(price); const creditCount = type === "MONTHLY" ? undefined : Number(credits); if (!name.trim() || !Number.isFinite(amount) || amount <= 0 || (creditCount !== undefined && (!Number.isInteger(creditCount) || creditCount < 1))) return Alert.alert(t("billing.invalid")); try { await createPlan.mutateAsync({ name: name.trim(), type, price: amount, creditCount, unusedCreditPolicy: type === "WEEKLY" ? policy : undefined, carryForwardDays: policy === "CARRY_FORWARD" ? 30 : undefined, bookingRequiresApproval: true }); setName(""); setPrice(""); } catch (error) { Alert.alert(t("billing.failed"), error instanceof Error ? error.message : t("auth.tryAgain")); } };
  return <AppScreen><AppText variant="title">{t("billing.title")}</AppText><View style={styles.form}><AppText variant="heading">{t("billing.createPlan")}</AppText><TextInput style={styles.input} placeholder={t("billing.planName")} value={name} onChangeText={setName} /><View style={styles.row}>{planTypes.map((item) => <Button key={item} variant={item === type ? "primary" : "secondary"} onPress={() => { setType(item); if (item === "DAILY") setCredits("1"); }}>{t(servicePlanTypeKey(item))}</Button>)}</View><TextInput style={styles.input} placeholder={t("billing.price")} keyboardType="numeric" value={price} onChangeText={setPrice} />{type !== "MONTHLY" && <TextInput style={styles.input} placeholder={t("billing.days")} keyboardType="numeric" value={credits} onChangeText={setCredits} />}{type === "WEEKLY" && <View style={styles.row}><Button variant={policy === "EXPIRE" ? "primary" : "secondary"} onPress={() => setPolicy("EXPIRE")}>{t("billing.expire")}</Button><Button variant={policy === "CARRY_FORWARD" ? "primary" : "secondary"} onPress={() => setPolicy("CARRY_FORWARD")}>{t("billing.carry")}</Button></View>}<Button loading={createPlan.isPending} onPress={() => void submitPlan()}>{t("billing.savePlan")}</Button></View><AppText variant="heading">{t("billing.activePlans")}</AppText>{plans.data?.map((plan) => <View key={plan.id} style={styles.card}><AppText variant="label">{plan.name}</AppText><AppText>{t(servicePlanTypeKey(plan.type))} · {formatCurrency(plan.price)}</AppText></View>)}<AppText variant="heading">{t("billing.pendingInvoices")}</AppText>{invoices.data?.filter((invoice) => invoice.status === "PENDING").map((invoice) => <View key={invoice.id} style={styles.card}><AppText variant="label">{invoice.invoiceNumber} · {invoice.childName}</AppText><AppText>{formatCurrency(invoice.totalAmount)} · {t("tenant.dueDate", { date: formatDate(invoice.dueDate) })}</AppText><Button loading={markPaid.isPending} onPress={() => void markPaid.mutateAsync(invoice.id)}>{t("billing.markPaid")}</Button></View>)}</AppScreen>;
}
const styles = StyleSheet.create({ form: { gap: spacing.sm, padding: spacing.md, borderRadius: radius.md, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border }, input: { minHeight: 48, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, paddingHorizontal: 12, backgroundColor: colors.surface }, row: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm }, card: { gap: spacing.sm, padding: spacing.md, borderRadius: radius.md, backgroundColor: colors.surfaceTint } });
