import { useState } from "react";
import { Alert, StyleSheet, TextInput, View } from "react-native";
import { router } from "expo-router";
import { AppText, Button, Screen, spacing } from "@daycare/ui";
import type { ServicePlanType, UnusedCreditPolicy } from "@daycare/core";
import { useCreateServicePlan, useInvoices, useMarkInvoicePaid, useServicePlans } from "@/booking/useBooking";

const planTypes: ServicePlanType[] = ["DAILY", "WEEKLY", "MONTHLY"];
export default function BillingAdminScreen() {
  const plans = useServicePlans(); const invoices = useInvoices(); const createPlan = useCreateServicePlan(); const markPaid = useMarkInvoicePaid();
  const [name, setName] = useState(""); const [price, setPrice] = useState(""); const [type, setType] = useState<ServicePlanType>("DAILY"); const [credits, setCredits] = useState("1"); const [policy, setPolicy] = useState<UnusedCreditPolicy>("EXPIRE");
  const submitPlan = async () => { const amount = Number(price); const creditCount = type === "MONTHLY" ? undefined : Number(credits); if (!name.trim() || !Number.isFinite(amount) || amount <= 0 || (creditCount !== undefined && (!Number.isInteger(creditCount) || creditCount < 1))) return Alert.alert("Data paket belum valid"); try { await createPlan.mutateAsync({ name: name.trim(), type, price: amount, creditCount, unusedCreditPolicy: type === "WEEKLY" ? policy : undefined, carryForwardDays: policy === "CARRY_FORWARD" ? 30 : undefined, bookingRequiresApproval: true }); setName(""); setPrice(""); } catch (error) { Alert.alert("Tidak dapat membuat paket", error instanceof Error ? error.message : "Silakan coba lagi."); } };
  return <Screen header={<Button variant="ghost" onPress={() => router.back()}>Kembali</Button>}><AppText variant="title">Paket dan tagihan</AppText><View style={styles.form}><AppText variant="heading">Buat paket layanan</AppText><TextInput style={styles.input} placeholder="Nama paket" value={name} onChangeText={setName} /><View style={styles.row}>{planTypes.map((item) => <Button key={item} variant={item === type ? "primary" : "secondary"} onPress={() => { setType(item); if (item === "DAILY") setCredits("1"); }}>{item}</Button>)}</View><TextInput style={styles.input} placeholder="Harga" keyboardType="numeric" value={price} onChangeText={setPrice} />{type !== "MONTHLY" && <TextInput style={styles.input} placeholder="Jumlah hari" keyboardType="numeric" value={credits} onChangeText={setCredits} />}{type === "WEEKLY" && <View style={styles.row}><Button variant={policy === "EXPIRE" ? "primary" : "secondary"} onPress={() => setPolicy("EXPIRE")}>Sisa hangus</Button><Button variant={policy === "CARRY_FORWARD" ? "primary" : "secondary"} onPress={() => setPolicy("CARRY_FORWARD")}>Sisa dipindahkan</Button></View>}<Button loading={createPlan.isPending} onPress={() => void submitPlan()}>Simpan paket</Button></View><AppText variant="heading">Paket aktif</AppText>{plans.data?.map((plan) => <View key={plan.id} style={styles.card}><AppText variant="label">{plan.name}</AppText><AppText>{plan.type} · Rp{plan.price.toLocaleString("id-ID")}</AppText></View>)}<AppText variant="heading">Tagihan menunggu pembayaran</AppText>{invoices.data?.filter((invoice) => invoice.status === "PENDING").map((invoice) => <View key={invoice.id} style={styles.card}><AppText variant="label">{invoice.invoiceNumber} · {invoice.childName}</AppText><AppText>Rp{invoice.totalAmount.toLocaleString("id-ID")} · jatuh tempo {invoice.dueDate}</AppText><Button loading={markPaid.isPending} onPress={() => void markPaid.mutateAsync(invoice.id)}>Tandai sudah dibayar</Button></View>)}</Screen>;
}
const styles = StyleSheet.create({ form: { gap: spacing.sm, padding: spacing.md, borderRadius: 12, backgroundColor: "#FFF" }, input: { minHeight: 48, borderWidth: 1, borderColor: "#D0D5DD", borderRadius: 12, paddingHorizontal: 12, backgroundColor: "#FFF" }, row: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm }, card: { gap: spacing.sm, padding: spacing.md, borderRadius: 12, backgroundColor: "#FFF" } });
