import { useState } from "react";
import { Alert, StyleSheet, TextInput, View } from "react-native";
import { useRouter } from "expo-router";
import { SafeRedirect as Redirect } from "@/navigation/SafeRedirect";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AppText, BackButton, Button, colors, radius, spacing } from "@daycare/ui";
import type { CreateServicePlanDiscountInput, UpsertServicePlanTemplateInput } from "@daycare/api-client";
import type { ServicePlanDiscountKind, ServicePlanDiscountType, ServicePlanType, UnusedCreditPolicy } from "@daycare/core";
import { AppScreen } from "@/navigation/AppScreen";
import { useCreateServicePlan, useInvoices, useMarkInvoicePaid, useServicePlans } from "@/booking/useBooking";
import { useAuth } from "@/auth/AuthProvider";
import { useI18n } from "@/i18n/I18nProvider";
import { servicePlanTypeKey, type TranslationKey } from "@/i18n/translations";
import { DatePicker } from "@/date-picker/DatePicker";

const planTypes: ServicePlanType[] = ["DAILY", "WEEKLY", "MONTHLY"];
const discountKinds: ServicePlanDiscountKind[] = ["AUTOMATIC", "PROMO_CODE"];
const discountTypes: ServicePlanDiscountType[] = ["PERCENTAGE", "FIXED_AMOUNT"];
type Translate = (key: TranslationKey) => string;
type PlanFields = { name: string; price: string; type: ServicePlanType; credits: string; policy: UnusedCreditPolicy; carryDays: string; capacity: string };
const emptyPlanFields = (): PlanFields => ({ name: "", price: "", type: "DAILY", credits: "1", policy: "EXPIRE", carryDays: "30", capacity: "" });
const optionalPositiveInteger = (value: string) => value.trim() ? Number(value) : undefined;

export default function BillingAdminScreen() {
  const router = useRouter();
  const { api, profile, organizationId } = useAuth();
  const { t, formatCurrency, formatDate } = useI18n();
  const membership = profile?.memberships.find((item) => item.organizationId === organizationId);
  const canManage = membership?.active === true;
  const client = useQueryClient();
  const plans = useServicePlans(); const invoices = useInvoices(); const createPlan = useCreateServicePlan(); const markPaid = useMarkInvoicePaid();
  const branches = useQuery({ queryKey: ["tenant-branches", organizationId], queryFn: () => api.branches(), enabled: membership?.role === "STAFF_ADMIN" });
  const capacities = useQuery({ queryKey: ["branch-capacities", organizationId], queryFn: () => api.branchCapacities(), enabled: membership?.role === "STAFF_ADMIN" });
  const templates = useQuery({ queryKey: ["service-plan-templates", organizationId], queryFn: () => api.servicePlanTemplates(), enabled: membership?.role === "STAFF_ADMIN" });
  const [selectedPlanId, setSelectedPlanId] = useState<string>();
  const discounts = useQuery({ queryKey: ["service-plan-discounts", organizationId, selectedPlanId], queryFn: () => api.servicePlanDiscounts(selectedPlanId!), enabled: membership?.role === "STAFF_ADMIN" && Boolean(selectedPlanId) });
  const refresh = (key: string) => () => client.invalidateQueries({ queryKey: [key, organizationId] });
  const setCapacity = useMutation({ mutationFn: ({ branchId, dailyCapacity }: { branchId: string; dailyCapacity: number }) => api.setBranchCapacity(branchId, dailyCapacity), onSuccess: refresh("branch-capacities") });
  const createTemplate = useMutation({ mutationFn: api.createServicePlanTemplate.bind(api), onSuccess: refresh("service-plan-templates") });
  const updateTemplate = useMutation({ mutationFn: ({ id, input }: { id: string; input: UpsertServicePlanTemplateInput }) => api.updateServicePlanTemplate(id, input), onSuccess: refresh("service-plan-templates") });
  const deleteTemplate = useMutation({ mutationFn: api.deleteServicePlanTemplate.bind(api), onSuccess: refresh("service-plan-templates") });
  const createDiscount = useMutation({ mutationFn: ({ planId, input }: { planId: string; input: CreateServicePlanDiscountInput }) => api.createServicePlanDiscount(planId, input), onSuccess: () => client.invalidateQueries({ queryKey: ["service-plan-discounts", organizationId, selectedPlanId] }) });
  const deactivateDiscount = useMutation({ mutationFn: ({ planId, discountId }: { planId: string; discountId: string }) => api.deactivateServicePlanDiscount(planId, discountId), onSuccess: () => client.invalidateQueries({ queryKey: ["service-plan-discounts", organizationId, selectedPlanId] }) });
  const [plan, setPlan] = useState<PlanFields>(emptyPlanFields());
  const [template, setTemplate] = useState<PlanFields>(emptyPlanFields());
  const [editingTemplateId, setEditingTemplateId] = useState<string>();
  const [branchValues, setBranchValues] = useState<Record<string, string>>({});
  const [discount, setDiscount] = useState({ name: "", kind: "AUTOMATIC" as ServicePlanDiscountKind, promoCode: "", type: "PERCENTAGE" as ServicePlanDiscountType, value: "", startsOn: "", endsOn: "", usageLimit: "" });
  const [form, setForm] = useState<"plan" | "template" | "discount" | null>(null);
  const [editingBranchId, setEditingBranchId] = useState<string>();
  if (!profile) return null;
  if (membership?.role !== "STAFF_ADMIN") return <Redirect href="/home" />;

  const asPlanInput = (fields: PlanFields) => {
    const price = fields.price.trim() ? Number(fields.price) : undefined;
    const creditCount = fields.type === "MONTHLY" ? undefined : Number(fields.credits);
    const dailyCapacity = optionalPositiveInteger(fields.capacity);
    const carryForwardDays = fields.type === "WEEKLY" && fields.policy === "CARRY_FORWARD" ? Number(fields.carryDays) : undefined;
    if (!fields.name.trim() || (price !== undefined && (!Number.isFinite(price) || price <= 0)) || (creditCount !== undefined && (!Number.isInteger(creditCount) || creditCount < 1)) || (dailyCapacity !== undefined && (!Number.isInteger(dailyCapacity) || dailyCapacity < 1)) || (carryForwardDays !== undefined && (!Number.isInteger(carryForwardDays) || carryForwardDays < 1))) return undefined;
    return { name: fields.name.trim(), type: fields.type, price, creditCount, unusedCreditPolicy: fields.type === "WEEKLY" ? fields.policy : undefined, carryForwardDays, bookingRequiresApproval: true, dailyCapacity };
  };
  const savePlan = async () => { const input = asPlanInput(plan); if (!input || input.price === undefined) return Alert.alert(t("billing.invalid")); const planInput = { ...input, price: input.price }; try { await createPlan.mutateAsync(planInput); await client.invalidateQueries({ queryKey: ["service-plans", organizationId] }); setPlan(emptyPlanFields()); setForm(null); } catch (error) { Alert.alert(t("billing.failed"), error instanceof Error ? error.message : t("auth.tryAgain")); } };
  const useTemplate = (item: { name: string; type: ServicePlanType; suggestedPrice?: number | null; creditCount?: number | null; unusedCreditPolicy?: UnusedCreditPolicy | null; carryForwardDays?: number | null; dailyCapacity?: number | null }) => { setPlan({ name: item.name, type: item.type, price: item.suggestedPrice?.toString() ?? "", credits: item.creditCount?.toString() ?? (item.type === "DAILY" ? "1" : ""), policy: item.unusedCreditPolicy ?? "EXPIRE", carryDays: item.carryForwardDays?.toString() ?? "30", capacity: item.dailyCapacity?.toString() ?? "" }); setForm("plan"); };
  const editTemplate = (item: { id: string; name: string; type: ServicePlanType; suggestedPrice?: number | null; creditCount?: number | null; unusedCreditPolicy?: UnusedCreditPolicy | null; carryForwardDays?: number | null; dailyCapacity?: number | null }) => { setEditingTemplateId(item.id); setTemplate({ name: item.name, type: item.type, price: item.suggestedPrice?.toString() ?? "", credits: item.creditCount?.toString() ?? (item.type === "DAILY" ? "1" : ""), policy: item.unusedCreditPolicy ?? "EXPIRE", carryDays: item.carryForwardDays?.toString() ?? "30", capacity: item.dailyCapacity?.toString() ?? "" }); setForm("template"); };
  const saveTemplate = async () => { const input = asPlanInput(template); if (!input) return Alert.alert(t("billing.invalid")); const { price: suggestedPrice, ...rest } = input; try { if (editingTemplateId) await updateTemplate.mutateAsync({ id: editingTemplateId, input: { ...rest, suggestedPrice } }); else await createTemplate.mutateAsync({ ...rest, suggestedPrice }); setEditingTemplateId(undefined); setTemplate(emptyPlanFields()); setForm(null); } catch (error) { Alert.alert(t("billing.templateFailed"), error instanceof Error ? error.message : t("auth.tryAgain")); } };
  const saveCapacity = async (branchId: string) => { const dailyCapacity = Number(branchValues[branchId]); if (!Number.isInteger(dailyCapacity) || dailyCapacity < 1) return Alert.alert(t("billing.invalidCapacity")); try { await setCapacity.mutateAsync({ branchId, dailyCapacity }); setEditingBranchId(undefined); } catch (error) { Alert.alert(t("billing.capacityFailed"), error instanceof Error ? error.message : t("auth.tryAgain")); } };
  const saveDiscount = async () => { if (!selectedPlanId) return Alert.alert(t("billing.selectPlan")); const value = Number(discount.value); const usageLimit = optionalPositiveInteger(discount.usageLimit); if (!discount.name.trim() || !Number.isFinite(value) || value <= 0 || (discount.type === "PERCENTAGE" && value >= 100) || (discount.kind === "PROMO_CODE" && !discount.promoCode.trim()) || (usageLimit !== undefined && (!Number.isInteger(usageLimit) || usageLimit < 1))) return Alert.alert(t("billing.invalidDiscount")); const input: CreateServicePlanDiscountInput = { kind: discount.kind, name: discount.name.trim(), promoCode: discount.kind === "PROMO_CODE" ? discount.promoCode.trim() : undefined, type: discount.type, value, startsOn: discount.startsOn.trim() || undefined, endsOn: discount.endsOn.trim() || undefined, usageLimit: discount.kind === "PROMO_CODE" ? usageLimit : undefined }; try { await createDiscount.mutateAsync({ planId: selectedPlanId, input }); setDiscount({ name: "", kind: "AUTOMATIC", promoCode: "", type: "PERCENTAGE", value: "", startsOn: "", endsOn: "", usageLimit: "" }); setForm(null); } catch (error) { Alert.alert(t("billing.discountFailed"), error instanceof Error ? error.message : t("auth.tryAgain")); } };

  return <AppScreen showBottomNavigation={false} title={t("billing.title")} header={<BackButton accessibilityLabel={t("common.back")} onPress={() => router.back()} />}>
    {!canManage && <AppText tone="muted">{t("staffOperations.readOnly")}</AppText>}
    {canManage && <Button onPress={() => { setPlan(emptyPlanFields()); setForm("plan"); }}>{t("billing.createPlan")}</Button>}
    {canManage && form === "plan" && <View style={styles.form}><AppText variant="heading">{t("billing.createPlan")}</AppText><PlanForm fields={plan} setFields={setPlan} t={t} priceLabel="billing.price" /><View style={styles.row}><Button loading={createPlan.isPending} onPress={() => void savePlan()}>{t("billing.savePlan")}</Button><Button variant="secondary" onPress={() => setForm(null)}>{t("common.cancel")}</Button></View></View>}
    <AppText variant="heading">{t("billing.templates")}</AppText><AppText tone="muted">{t("billing.templatesDescription")}</AppText>
    {templates.data?.map((item) => <View key={item.id} style={styles.card}><AppText variant="label">{item.name}</AppText><AppText tone="muted">{t(servicePlanTypeKey(item.type))}{item.suggestedPrice ? ` · ${formatCurrency(item.suggestedPrice)}` : ""}</AppText>{canManage && <View style={styles.row}><Button variant="secondary" onPress={() => useTemplate(item)}>{t("billing.useTemplate")}</Button>{item.source === "TENANT" && <Button variant="secondary" onPress={() => editTemplate(item)}>{t("billing.editTemplate")}</Button>}{item.source === "TENANT" && <Button variant="danger" loading={deleteTemplate.isPending} onPress={() => void deleteTemplate.mutateAsync(item.id)}>{t("billing.deleteTemplate")}</Button>}</View>}</View>)}
    {canManage && <Button variant="secondary" onPress={() => { setEditingTemplateId(undefined); setTemplate(emptyPlanFields()); setForm("template"); }}>{t("billing.createTemplate")}</Button>}
    {canManage && form === "template" && <View style={styles.form}><AppText variant="heading">{t(editingTemplateId ? "billing.editTemplate" : "billing.createTemplate")}</AppText><PlanForm fields={template} setFields={setTemplate} t={t} priceLabel="billing.suggestedPrice" /><View style={styles.row}><Button loading={createTemplate.isPending || updateTemplate.isPending} onPress={() => void saveTemplate()}>{t("common.save")}</Button><Button variant="secondary" onPress={() => { setEditingTemplateId(undefined); setTemplate(emptyPlanFields()); setForm(null); }}>{t("common.cancel")}</Button></View></View>}
    <AppText variant="heading">{t("billing.branchCapacity")}</AppText><AppText tone="muted">{t("billing.branchCapacityDescription")}</AppText>
    {branches.data?.filter((branch) => branch.active).map((branch) => { const configured = capacities.data?.find((item) => item.branchId === branch.id)?.dailyCapacity; const value = branchValues[branch.id] ?? configured?.toString() ?? ""; return <View key={branch.id} style={styles.card}><AppText variant="label">{branch.name}</AppText>{canManage && editingBranchId === branch.id ? <><TextInput style={styles.input} placeholder={t("billing.dailyCapacity")} keyboardType="numeric" value={value} onChangeText={(next) => setBranchValues((current) => ({ ...current, [branch.id]: next }))} /><View style={styles.row}><Button loading={setCapacity.isPending} onPress={() => void saveCapacity(branch.id)}>{t("billing.saveCapacity")}</Button><Button variant="secondary" onPress={() => setEditingBranchId(undefined)}>{t("common.cancel")}</Button></View></> : canManage ? <><AppText tone="muted">{configured ?? "–"}</AppText><Button variant="secondary" onPress={() => setEditingBranchId(branch.id)}>{t("common.edit")}</Button></> : <AppText tone="muted">{configured ?? "–"}</AppText>}</View>; })}
    <AppText variant="heading">{t("billing.discounts")}</AppText><AppText tone="muted">{t("billing.discountsDescription")}</AppText><View style={styles.row}>{plans.data?.map((item) => <Button key={item.id} variant={item.id === selectedPlanId ? "primary" : "secondary"} onPress={() => { setSelectedPlanId(item.id); setForm((current) => current === "discount" ? null : current); }}>{item.name}</Button>)}</View>
    {canManage && selectedPlanId && <Button variant="secondary" onPress={() => { setDiscount({ name: "", kind: "AUTOMATIC", promoCode: "", type: "PERCENTAGE", value: "", startsOn: "", endsOn: "", usageLimit: "" }); setForm("discount"); }}>{t("billing.discounts")}</Button>}
    {canManage && selectedPlanId && form === "discount" && <View style={styles.form}><TextInput style={styles.input} placeholder={t("billing.discountName")} value={discount.name} onChangeText={(name) => setDiscount((current) => ({ ...current, name }))} /><Choice values={discountKinds} value={discount.kind} onChange={(kind) => setDiscount((current) => ({ ...current, kind }))} labels={{ AUTOMATIC: t("billing.automatic"), PROMO_CODE: t("billing.promo") }} />{discount.kind === "PROMO_CODE" && <TextInput style={styles.input} autoCapitalize="characters" placeholder={t("billing.promoCode")} value={discount.promoCode} onChangeText={(promoCode) => setDiscount((current) => ({ ...current, promoCode }))} />}<Choice values={discountTypes} value={discount.type} onChange={(type) => setDiscount((current) => ({ ...current, type }))} labels={{ PERCENTAGE: t("billing.percentage"), FIXED_AMOUNT: t("billing.fixedAmount") }} /><TextInput style={styles.input} placeholder={t("billing.discountValue")} keyboardType="numeric" value={discount.value} onChangeText={(value) => setDiscount((current) => ({ ...current, value }))} /><DatePicker placeholder={t("billing.startsOn")} value={discount.startsOn} onChange={(startsOn) => setDiscount((current) => ({ ...current, startsOn }))} maximumDate={discount.endsOn || undefined} onClear={() => setDiscount((current) => ({ ...current, startsOn: "" }))} clearAccessibilityLabel={t("common.clear")} /><DatePicker placeholder={t("billing.endsOn")} value={discount.endsOn} onChange={(endsOn) => setDiscount((current) => ({ ...current, endsOn }))} minimumDate={discount.startsOn || undefined} onClear={() => setDiscount((current) => ({ ...current, endsOn: "" }))} clearAccessibilityLabel={t("common.clear")} />{discount.kind === "PROMO_CODE" && <TextInput style={styles.input} placeholder={t("billing.usageLimit")} keyboardType="numeric" value={discount.usageLimit} onChangeText={(usageLimit) => setDiscount((current) => ({ ...current, usageLimit }))} />}<View style={styles.row}><Button loading={createDiscount.isPending} onPress={() => void saveDiscount()}>{t("billing.saveDiscount")}</Button><Button variant="secondary" onPress={() => setForm(null)}>{t("common.cancel")}</Button></View></View>}
    {discounts.data?.map((item) => <View key={item.id} style={styles.card}><AppText variant="label">{item.name}{item.promoCode ? ` · ${item.promoCode}` : ""}</AppText><AppText tone="muted">{item.type === "PERCENTAGE" ? `${item.value}%` : formatCurrency(item.value)} · {item.active ? t("status.ACTIVE") : t("billing.inactive")}</AppText>{canManage && item.active && selectedPlanId && <Button variant="danger" loading={deactivateDiscount.isPending} onPress={() => void deactivateDiscount.mutateAsync({ planId: selectedPlanId, discountId: item.id })}>{t("billing.deactivate")}</Button>}</View>)}
    <AppText variant="heading">{t("billing.activePlans")}</AppText>{plans.data?.map((item) => <View key={item.id} style={styles.card}><AppText variant="label">{item.name}</AppText><AppText>{t(servicePlanTypeKey(item.type))} · {formatCurrency(item.price)}</AppText></View>)}
    <AppText variant="heading">{t("billing.pendingInvoices")}</AppText>{invoices.data?.filter((item) => item.status === "PENDING").map((item) => <View key={item.id} style={styles.card}><AppText variant="label">{item.invoiceNumber} · {item.childName}</AppText><AppText>{formatCurrency(item.totalAmount)} · {t("tenant.dueDate", { date: formatDate(item.dueDate) })}</AppText>{canManage && <Button loading={markPaid.isPending} onPress={() => void markPaid.mutateAsync(item.id)}>{t("billing.markPaid")}</Button>}</View>)}
  </AppScreen>;
}

function PlanForm({ fields, setFields, t, priceLabel }: { fields: PlanFields; setFields: (value: PlanFields) => void; t: Translate; priceLabel: TranslationKey }) {
  const update = (patch: Partial<PlanFields>) => setFields({ ...fields, ...patch });
  return <><TextInput style={styles.input} placeholder={t(fields.name === "" ? "billing.planName" : "billing.planName")} value={fields.name} onChangeText={(name) => update({ name })} /><View style={styles.row}>{planTypes.map((item) => <Button key={item} variant={item === fields.type ? "primary" : "secondary"} onPress={() => update({ type: item, credits: item === "DAILY" ? "1" : fields.credits })}>{t(servicePlanTypeKey(item))}</Button>)}</View><TextInput style={styles.input} placeholder={t(priceLabel)} keyboardType="numeric" value={fields.price} onChangeText={(price) => update({ price })} /><TextInput style={styles.input} placeholder={t("billing.dailyCapacity")} keyboardType="numeric" value={fields.capacity} onChangeText={(capacity) => update({ capacity })} />{fields.type !== "MONTHLY" && <TextInput style={styles.input} placeholder={t("billing.days")} keyboardType="numeric" value={fields.credits} onChangeText={(credits) => update({ credits })} />}{fields.type === "WEEKLY" && <><View style={styles.row}><Button variant={fields.policy === "EXPIRE" ? "primary" : "secondary"} onPress={() => update({ policy: "EXPIRE" })}>{t("billing.expire")}</Button><Button variant={fields.policy === "CARRY_FORWARD" ? "primary" : "secondary"} onPress={() => update({ policy: "CARRY_FORWARD" })}>{t("billing.carry")}</Button></View>{fields.policy === "CARRY_FORWARD" && <TextInput style={styles.input} placeholder={t("billing.carryForwardDays")} keyboardType="numeric" value={fields.carryDays} onChangeText={(carryDays) => update({ carryDays })} />}</>}</>;
}

function Choice<T extends string>({ values, value, onChange, labels }: { values: readonly T[]; value: T; onChange: (value: T) => void; labels: Record<T, string> }) { return <View style={styles.row}>{values.map((item) => <Button key={item} variant={item === value ? "primary" : "secondary"} onPress={() => onChange(item)}>{labels[item]}</Button>)}</View>; }

const styles = StyleSheet.create({ form: { gap: spacing.sm, padding: spacing.md, borderRadius: radius.md, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border }, input: { minHeight: 48, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, paddingHorizontal: spacing.sm, backgroundColor: colors.surface }, row: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm }, card: { gap: spacing.sm, padding: spacing.md, borderRadius: radius.md, backgroundColor: colors.surfaceTint } });
