import { useEffect, useState, type ReactNode } from "react";
import { Pressable, ScrollView, StyleSheet, TextInput, View } from "react-native";
import { useLocalSearchParams, useRouter } from "expo-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AppText, BackButton, Button, ToggleSwitch, colors, publishInlineFeedback, spacing } from "@daycare/ui";
import { AppScreen } from "@/navigation/AppScreen";
import { SafeRedirect as Redirect } from "@/navigation/SafeRedirect";
import { useAuth } from "@/auth/AuthProvider";
import { useI18n } from "@/i18n/I18nProvider";
import { hasOfferingCapability, useUiAccessContext } from "@/education/useUiAccessContext";

const MAX_PRICE = 1_000_000_000;
const digitsOnly = (value: string) => value.replace(/\D/g, "");
const formatThousands = (digits: string) => digits.replace(/\B(?=(\d{3})+(?!\d))/g, ".");
const formatPriceInput = (value: string) => { const digits = digitsOnly(value); return digits ? formatThousands(String(Math.min(MAX_PRICE, Number(digits)))) : ""; };
function parsePrice(value: string): number | undefined { const digits = digitsOnly(value); return digits ? Number(digits) : undefined; }

export default function PrivateTutoringServiceFormScreen() {
  const { serviceId } = useLocalSearchParams<{ serviceId?: string }>(); const router = useRouter(); const { api, profile, organizationId } = useAuth(); const { t } = useI18n(); const client = useQueryClient(); const membership = profile?.memberships.find((item) => item.organizationId === organizationId);
  const access = useUiAccessContext(Boolean(membership)); const hasAcademicOffering = hasOfferingCapability(access.data, "ACADEMIC_CURRICULUM");
  const services = useQuery({ queryKey: ["private-tutoring-admin-services", organizationId], queryFn: () => api.privateTutoringServices(), enabled: membership?.role === "STAFF_ADMIN" && hasAcademicOffering }); const branches = useQuery({ queryKey: ["tenant-branches", organizationId], queryFn: () => api.branches(), enabled: Boolean(organizationId && hasAcademicOffering) }); const levels = useQuery({ queryKey: ["learning-levels", organizationId], queryFn: () => api.learningLevels(), enabled: Boolean(organizationId && hasAcademicOffering) }); const tutors = useQuery({ queryKey: ["private-tutoring-tutors", organizationId], queryFn: () => api.privateTutors(), enabled: Boolean(organizationId && hasAcademicOffering) });
  const existing = services.data?.find((item) => item.id === serviceId); const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [branchId, setBranchId] = useState(""); const [minAge, setMinAge] = useState("0"); const [maxAge, setMaxAge] = useState("120"); const [duration, setDuration] = useState("60"); const [dailyPrice, setDailyPrice] = useState(""); const [weeklyPrice, setWeeklyPrice] = useState(""); const [monthlyPrice, setMonthlyPrice] = useState(""); const [levelIds, setLevelIds] = useState<string[]>([]); const [tutorIds, setTutorIds] = useState<string[]>([]); const [active, setActive] = useState(true); const [openInfo, setOpenInfo] = useState<string | null>(null);
  useEffect(() => { if (!existing) return; setName(existing.name); setDescription(existing.description); setBranchId(existing.branchId); setMinAge(String(existing.minAgeMonths)); setMaxAge(String(existing.maxAgeMonths)); setDuration(String(existing.durationMinutes)); setDailyPrice(existing.dailyPrice != null ? formatThousands(String(existing.dailyPrice)) : ""); setWeeklyPrice(existing.weeklyPrice != null ? formatThousands(String(existing.weeklyPrice)) : ""); setMonthlyPrice(existing.monthlyPrice != null ? formatThousands(String(existing.monthlyPrice)) : ""); setLevelIds(existing.learningLevelIds); setTutorIds(existing.tutors.map((item) => item.id)); setActive(existing.active); }, [existing]);
  const save = useMutation({ mutationFn: (input: Parameters<typeof api.createPrivateTutoringService>[0]) => existing ? api.updatePrivateTutoringService(existing.id, input) : api.createPrivateTutoringService(input), onSuccess: () => { void client.invalidateQueries({ queryKey: ["private-tutoring-admin-services", organizationId] }); router.back(); } });
  const activeLevels = levels.data?.filter((item) => item.active && item.source === "TENANT") ?? [];
  const activeTutors = tutors.data?.filter((item) => item.active) ?? [];
  if (!profile) return null; if (membership?.role !== "STAFF_ADMIN") return <Redirect href="/home" />; if (!access.isLoading && !hasAcademicOffering) return <Redirect href="/staff-admin" />;
  const toggle = (id: string, selected: string[], setSelected: (value: string[]) => void) => setSelected(selected.includes(id) ? selected.filter((item) => item !== id) : [...selected, id]);
  const submit = () => {
    const prices = [parsePrice(dailyPrice), parsePrice(weeklyPrice), parsePrice(monthlyPrice)];
    const numeric = [Number(minAge), Number(maxAge), Number(duration), ...prices.filter((value): value is number => value !== undefined)];
    if (!branchId || !name.trim() || numeric.some((item) => !Number.isFinite(item)) || Number(minAge) > Number(maxAge) || Number(duration) < 15 || prices.every((value) => value === undefined) || prices.some((value) => value !== undefined && value <= 0) || !levelIds.length || !tutorIds.length) return publishInlineFeedback(t("privateTutoring.serviceRequired"));
    void save.mutateAsync({ branchId, name: name.trim(), description: description.trim(), minAgeMonths: Number(minAge), maxAgeMonths: Number(maxAge), durationMinutes: Number(duration), dailyPrice: prices[0] ?? null, weeklyPrice: prices[1] ?? null, monthlyPrice: prices[2] ?? null, learningLevelIds: levelIds, tutorIds, active }).catch((error) => publishInlineFeedback(t("privateTutoring.saveFailed"), error instanceof Error ? error.message : t("auth.tryAgain")));
  };
  const infoAction = (id: string) => t(openInfo === id ? "privateTutoring.hideInfo" : "privateTutoring.showInfo");
  const toggleInfo = (id: string) => setOpenInfo((current) => current === id ? null : id);
  return <AppScreen showBottomNavigation={false} title={t(existing ? "privateTutoring.editService" : "privateTutoring.addService")} header={<BackButton accessibilityLabel={t("common.back")} onPress={() => router.back()} />}><ScrollView contentContainerStyle={styles.content}>
    <TutoringFormField id="name" label={t("privateTutoring.serviceName")} info={t("privateTutoring.serviceNameInfo")} infoAction={infoAction("name")} expanded={openInfo === "name"} onToggle={() => toggleInfo("name")}><TextInput style={styles.input} placeholder={t("privateTutoring.serviceName")} value={name} onChangeText={setName} /></TutoringFormField>
    <TutoringFormField id="description" label={t("privateTutoring.serviceDescription")} info={t("privateTutoring.serviceDescriptionInfo")} infoAction={infoAction("description")} expanded={openInfo === "description"} onToggle={() => toggleInfo("description")}><TextInput style={[styles.input, styles.note]} multiline placeholder={t("privateTutoring.serviceDescription")} value={description} onChangeText={setDescription} /></TutoringFormField>
    <TutoringFormField id="branch" label={t("privateTutoring.branch")} info={t("privateTutoring.branchInfo")} infoAction={infoAction("branch")} expanded={openInfo === "branch"} onToggle={() => toggleInfo("branch")}><View style={styles.options}>{branches.data?.filter((item) => item.active).map((item) => <Button key={item.id} variant={branchId === item.id ? "primary" : "secondary"} onPress={() => setBranchId(item.id)}>{item.name}</Button>)}</View></TutoringFormField>
    <TutoringFormField id="min-age" label={t("privateTutoring.minAge")} info={t("privateTutoring.minAgeInfo")} infoAction={infoAction("min-age")} expanded={openInfo === "min-age"} onToggle={() => toggleInfo("min-age")}><TextInput style={styles.input} inputMode="numeric" placeholder={t("privateTutoring.minAge")} value={minAge} onChangeText={setMinAge} /></TutoringFormField>
    <TutoringFormField id="max-age" label={t("privateTutoring.maxAge")} info={t("privateTutoring.maxAgeInfo")} infoAction={infoAction("max-age")} expanded={openInfo === "max-age"} onToggle={() => toggleInfo("max-age")}><TextInput style={styles.input} inputMode="numeric" placeholder={t("privateTutoring.maxAge")} value={maxAge} onChangeText={setMaxAge} /></TutoringFormField>
    <TutoringFormField id="duration" label={t("privateTutoring.durationMinutes")} info={t("privateTutoring.durationInfo")} infoAction={infoAction("duration")} expanded={openInfo === "duration"} onToggle={() => toggleInfo("duration")}><TextInput style={styles.input} inputMode="numeric" placeholder={t("privateTutoring.durationMinutes")} value={duration} onChangeText={setDuration} /></TutoringFormField>
    <TutoringFormField id="daily-price" label={t("privateTutoring.dailyPrice")} info={t("privateTutoring.dailyPriceInfo")} infoAction={infoAction("daily-price")} expanded={openInfo === "daily-price"} onToggle={() => toggleInfo("daily-price")}><PriceInput value={dailyPrice} onChangeText={setDailyPrice} /></TutoringFormField>
    <TutoringFormField id="weekly-price" label={t("privateTutoring.weeklyPrice")} info={t("privateTutoring.weeklyPriceInfo")} infoAction={infoAction("weekly-price")} expanded={openInfo === "weekly-price"} onToggle={() => toggleInfo("weekly-price")}><PriceInput value={weeklyPrice} onChangeText={setWeeklyPrice} /></TutoringFormField>
    <TutoringFormField id="monthly-price" label={t("privateTutoring.monthlyPrice")} info={t("privateTutoring.monthlyPriceInfo")} infoAction={infoAction("monthly-price")} expanded={openInfo === "monthly-price"} onToggle={() => toggleInfo("monthly-price")}><PriceInput value={monthlyPrice} onChangeText={setMonthlyPrice} /></TutoringFormField>
    <TutoringFormField id="levels" label={t("privateTutoring.learningLevels")} info={t("privateTutoring.learningLevelsInfo")} infoAction={infoAction("levels")} expanded={openInfo === "levels"} onToggle={() => toggleInfo("levels")}><View style={styles.options}>{activeLevels.map((item) => <Button key={item.id} variant={levelIds.includes(item.id) ? "primary" : "secondary"} onPress={() => toggle(item.id, levelIds, setLevelIds)}>{item.name}</Button>)}</View>{!levels.isFetching && activeLevels.length === 0 && <AppText tone="muted">{t("privateTutoring.noActiveLevels")}</AppText>}</TutoringFormField>
    <TutoringFormField id="tutors" label={t("privateTutoring.tutorSelection")} info={t("privateTutoring.tutorSelectionInfo")} infoAction={infoAction("tutors")} expanded={openInfo === "tutors"} onToggle={() => toggleInfo("tutors")}><View style={styles.options}>{activeTutors.map((item) => <Button key={item.id} variant={tutorIds.includes(item.id) ? "primary" : "secondary"} onPress={() => toggle(item.id, tutorIds, setTutorIds)}>{item.displayName}</Button>)}</View>{!tutors.isFetching && activeTutors.length === 0 && <AppText tone="muted">{t("privateTutoring.noActiveTutors")}</AppText>}</TutoringFormField>
    <TutoringFormField id="active" label={t("privateTutoring.status")} info={t("privateTutoring.activeInfo")} infoAction={infoAction("active")} expanded={openInfo === "active"} onToggle={() => toggleInfo("active")}><ToggleSwitch label={t("privateTutoring.status")} value={active} onValueChange={setActive} accessibilityLabel={t("privateTutoring.status")} description={t(active ? "privateTutoring.active" : "privateTutoring.inactive")} /></TutoringFormField>
    <Button loading={save.isPending} onPress={submit}>{t("common.save")}</Button>
  </ScrollView></AppScreen>;
}

type TutoringFormFieldProps = { id: string; label: string; info: string; infoAction: string; expanded: boolean; onToggle: () => void; children: ReactNode };

function TutoringFormField({ id, label, info, infoAction, expanded, onToggle, children }: TutoringFormFieldProps) {
  return <View style={styles.field}><View style={styles.fieldHeader}><AppText variant="label">{label}</AppText><Pressable accessibilityRole="button" accessibilityLabel={`${infoAction}: ${label}`} accessibilityState={{ expanded }} onPress={onToggle} style={({ pressed }) => [styles.infoToggle, pressed && styles.pressed]}><AppText variant="caption" tone="muted">ⓘ {infoAction}</AppText></Pressable></View>{expanded && <View nativeID={`${id}-info`} style={styles.info}><AppText variant="caption" tone="muted">{info}</AppText></View>}{children}</View>;
}

function PriceInput({ value, onChangeText }: { value: string; onChangeText: (value: string) => void }) {
  return <View style={styles.priceField}>
    <AppText tone="muted">Rp</AppText>
    <TextInput style={[styles.input, styles.priceInput]} inputMode="numeric" placeholder="0" value={value} onChangeText={(text) => onChangeText(formatPriceInput(text))} />
  </View>;
}

const styles = StyleSheet.create({ content: { gap: spacing.md }, field: { gap: spacing.xs }, fieldHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: spacing.sm }, info: { padding: spacing.sm, borderRadius: 12, backgroundColor: colors.surfaceTint }, infoToggle: { paddingVertical: spacing.xs, paddingHorizontal: spacing.sm }, pressed: { opacity: 0.7 }, options: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm }, input: { minHeight: 48, paddingHorizontal: spacing.sm, borderWidth: 1, borderColor: colors.border, borderRadius: 12, backgroundColor: colors.surface }, note: { minHeight: 96, paddingVertical: spacing.sm, textAlignVertical: "top" }, priceField: { flexDirection: "row", alignItems: "center", gap: spacing.xs }, priceInput: { flex: 1 } });
