import { useState } from "react";
import { Alert, StyleSheet, TextInput, View } from "react-native";
import { useLocalSearchParams, useRouter } from "expo-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AppText, BackButton, Button, colors, spacing } from "@daycare/ui";
import { AppScreen } from "@/navigation/AppScreen";
import { SafeRedirect as Redirect } from "@/navigation/SafeRedirect";
import { useAuth } from "@/auth/AuthProvider";
import { useI18n } from "@/i18n/I18nProvider";

export default function PrivateTutoringDecisionScreen() {
  const { requestId } = useLocalSearchParams<{ requestId: string }>(); const router = useRouter(); const { api, profile, organizationId } = useAuth(); const { t } = useI18n(); const client = useQueryClient(); const membership = profile?.memberships.find((item) => item.organizationId === organizationId); const requests = useQuery({ queryKey: ["private-tutoring-admin-requests", organizationId], queryFn: () => api.privateTutoringRequests(), enabled: membership?.role === "STAFF_ADMIN" }); const tutors = useQuery({ queryKey: ["private-tutoring-tutors", organizationId], queryFn: () => api.privateTutors(), enabled: membership?.role === "STAFF_ADMIN" }); const request = requests.data?.find((item) => item.id === requestId); const [tutorId, setTutorId] = useState(""); const [scheduledAt, setScheduledAt] = useState(""); const [reason, setReason] = useState("");
  const decide = useMutation({ mutationFn: (input: { approved: boolean; tutorId?: string; scheduledAt?: string; rejectionReason?: string }) => api.decidePrivateTutoringRequest(requestId, input), onSuccess: () => { void client.invalidateQueries({ queryKey: ["private-tutoring-admin-requests", organizationId] }); router.back(); } }); if (!profile) return null; if (membership?.role !== "STAFF_ADMIN") return <Redirect href="/home" />;
  const submit = (approved: boolean) => { if (approved && (!tutorId || !scheduledAt)) return Alert.alert(t("privateTutoring.decisionRequired")); if (!approved && !reason.trim()) return Alert.alert(t("privateTutoring.decisionRequired")); void decide.mutateAsync({ approved, tutorId: approved ? tutorId : undefined, scheduledAt: approved ? scheduledAt : undefined, rejectionReason: approved ? undefined : reason.trim() }).catch((error) => Alert.alert(t("privateTutoring.decideFailed"), error instanceof Error ? error.message : t("auth.tryAgain"))); };
  return <AppScreen showBottomNavigation={false} title={t("privateTutoring.schedule")} header={<BackButton accessibilityLabel={t("common.back")} onPress={() => router.back()} />}><View style={styles.content}><AppText variant="heading">{request?.serviceName} · {request?.childName}</AppText><AppText variant="label">{t("privateTutoring.selectTutor")}</AppText><View style={styles.options}>{tutors.data?.filter((item) => item.active).map((item) => <Button key={item.id} variant={tutorId === item.id ? "primary" : "secondary"} onPress={() => setTutorId(item.id)}>{item.displayName}</Button>)}</View><TextInput style={styles.input} placeholder="YYYY-MM-DDTHH:mm" value={scheduledAt} onChangeText={setScheduledAt} /><TextInput style={[styles.input, styles.note]} multiline placeholder={t("privateTutoring.rejectionReason")} value={reason} onChangeText={setReason} /><Button loading={decide.isPending} onPress={() => submit(true)}>{t("privateTutoring.approve")}</Button><Button variant="danger" disabled={decide.isPending} onPress={() => submit(false)}>{t("privateTutoring.reject")}</Button></View></AppScreen>;
}
const styles = StyleSheet.create({ content: { gap: spacing.md }, options: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm }, input: { minHeight: 48, paddingHorizontal: spacing.sm, borderWidth: 1, borderColor: colors.border, borderRadius: 12, backgroundColor: colors.surface }, note: { minHeight: 96, paddingVertical: spacing.sm, textAlignVertical: "top" } });
