import { useEffect, useState } from "react";
import { StyleSheet, View } from "react-native";
import { useLocalSearchParams, useRouter } from "expo-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AppText, BackButton, Button, Chip, TextField, ToggleSwitch, colors, spacing } from "@daycare/ui";
import { notify } from "@/notify/notify";
import { AppScreen } from "@/navigation/AppScreen";
import { SafeRedirect as Redirect } from "@/navigation/SafeRedirect";
import { useAuth } from "@/auth/AuthProvider";
import { useI18n } from "@/i18n/I18nProvider";
import { capitalizeWords } from "@/text/capitalizeWords";
import { hasOfferingCapability, useUiAccessContext } from "@/education/useUiAccessContext";

export default function PrivateTutorFormScreen() {
  const { tutorId } = useLocalSearchParams<{ tutorId?: string }>(); const router = useRouter(); const { api, profile, organizationId } = useAuth(); const { t } = useI18n(); const client = useQueryClient(); const membership = profile?.memberships.find((item) => item.organizationId === organizationId);
  const access = useUiAccessContext(Boolean(membership)); const hasAcademicOffering = hasOfferingCapability(access.data, "ACADEMIC_CURRICULUM");
  const tutors = useQuery({ queryKey: ["private-tutoring-tutors", organizationId], queryFn: () => api.privateTutors(), enabled: membership?.role === "STAFF_ADMIN" && hasAcademicOffering }); const users = useQuery({ queryKey: ["tenant-users", organizationId], queryFn: () => api.tenantUsers(), enabled: membership?.role === "STAFF_ADMIN" && hasAcademicOffering }); const existing = tutors.data?.find((item) => item.id === tutorId);
  const [type, setType] = useState<"STAFF" | "EXTERNAL">("EXTERNAL"); const [staffUserId, setStaffUserId] = useState(""); const [displayName, setDisplayName] = useState(""); const [bio, setBio] = useState(""); const [active, setActive] = useState(true);
  useEffect(() => { if (!existing) return; setType(existing.type); setStaffUserId(existing.staffUserId ?? ""); setBio(existing.bio); setDisplayName(existing.displayName); setActive(existing.active); }, [existing]);
  const save = useMutation({ mutationFn: (input: { type: "STAFF" | "EXTERNAL"; staffUserId?: string; displayName?: string; bio?: string; active: boolean }) => existing ? api.updatePrivateTutor(existing.id, input) : api.createPrivateTutor(input), onSuccess: () => { void client.invalidateQueries({ queryKey: ["private-tutoring-tutors", organizationId] }); router.back(); } });
  if (!profile) return null; if (membership?.role !== "STAFF_ADMIN") return <Redirect href="/home" />; if (!access.isLoading && !hasAcademicOffering) return <Redirect href="/staff-admin" />;
  const submit = () => { if ((type === "STAFF" && !staffUserId) || (type === "EXTERNAL" && !displayName.trim())) return notify(t("privateTutoring.tutorRequired"), undefined, "warning"); void save.mutateAsync({ type, staffUserId: type === "STAFF" ? staffUserId : undefined, displayName: type === "EXTERNAL" ? displayName.trim() : undefined, bio: bio.trim(), active }).catch((error) => notify(t("privateTutoring.saveFailed"), error instanceof Error ? error.message : t("auth.tryAgain"), "danger")); };
  return <AppScreen showBottomNavigation={false} title={t(existing ? "privateTutoring.editTutor" : "privateTutoring.addTutor")} header={<BackButton accessibilityLabel={t("common.back")} onPress={() => router.back()} />}><View style={styles.content}><AppText variant="label">{t("privateTutoring.type")}</AppText><View style={styles.options}><Chip label={t("privateTutoring.staffTutor")} selected={type === "STAFF"} onPress={() => setType("STAFF")} /><Chip label={t("privateTutoring.externalTutor")} selected={type === "EXTERNAL"} onPress={() => setType("EXTERNAL")} /></View>{type === "STAFF" ? <><AppText variant="label">{t("privateTutoring.staff")}</AppText><View style={styles.options}>{users.data?.filter((item) => item.role === "STAFF" && item.status === "ACTIVE" && item.userId).map((item) => <Chip key={item.userId} label={item.displayName ?? item.email ?? ""} selected={staffUserId === item.userId} onPress={() => setStaffUserId(item.userId!)} />)}</View></> : <TextField label={t("privateTutoring.tutorName")} autoCapitalize="words" value={displayName} onChangeText={(value) => setDisplayName(capitalizeWords(value))} />}<TextField label={t("privateTutoring.bio")} multiline value={bio} onChangeText={setBio} /><ToggleSwitch label={t("privateTutoring.status")} value={active} onValueChange={setActive} accessibilityLabel={t("privateTutoring.status")} description={t(active ? "privateTutoring.active" : "privateTutoring.inactive")} /><Button loading={save.isPending} onPress={submit}>{t("common.save")}</Button></View></AppScreen>;
}
const styles = StyleSheet.create({ content: { gap: spacing.md }, options: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm }, input: { minHeight: 48, paddingHorizontal: spacing.sm, borderWidth: 1, borderColor: colors.border, borderRadius: 12, backgroundColor: colors.surface }, note: { minHeight: 96, paddingVertical: spacing.sm, textAlignVertical: "top" } });
