import { useEffect, useState, type ReactNode } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, TextInput, View } from "react-native";
import { useLocalSearchParams, useRouter } from "expo-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AppText, BackButton, Button, colors, spacing } from "@daycare/ui";
import { AppScreen } from "@/navigation/AppScreen";
import { SafeRedirect as Redirect } from "@/navigation/SafeRedirect";
import { useAuth } from "@/auth/AuthProvider";
import { useI18n } from "@/i18n/I18nProvider";

export default function PrivateTutoringServiceFormScreen() {
  const { serviceId } = useLocalSearchParams<{ serviceId?: string }>(); const router = useRouter(); const { api, profile, organizationId } = useAuth(); const { t } = useI18n(); const client = useQueryClient(); const membership = profile?.memberships.find((item) => item.organizationId === organizationId);
  const services = useQuery({ queryKey: ["private-tutoring-admin-services", organizationId], queryFn: () => api.privateTutoringServices(), enabled: membership?.role === "STAFF_ADMIN" }); const branches = useQuery({ queryKey: ["tenant-branches", organizationId], queryFn: () => api.branches(), enabled: Boolean(organizationId) }); const levels = useQuery({ queryKey: ["learning-levels", organizationId], queryFn: () => api.learningLevels(), enabled: Boolean(organizationId) }); const tutors = useQuery({ queryKey: ["private-tutoring-tutors", organizationId], queryFn: () => api.privateTutors(), enabled: Boolean(organizationId) });
  const existing = services.data?.find((item) => item.id === serviceId); const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [branchId, setBranchId] = useState(""); const [minAge, setMinAge] = useState("0"); const [maxAge, setMaxAge] = useState("120"); const [duration, setDuration] = useState("60"); const [price, setPrice] = useState(""); const [levelIds, setLevelIds] = useState<string[]>([]); const [tutorIds, setTutorIds] = useState<string[]>([]); const [active, setActive] = useState(true); const [openInfo, setOpenInfo] = useState<string | null>(null);
  useEffect(() => { if (!existing) return; setName(existing.name); setDescription(existing.description); setBranchId(existing.branchId); setMinAge(String(existing.minAgeMonths)); setMaxAge(String(existing.maxAgeMonths)); setDuration(String(existing.durationMinutes)); setPrice(String(existing.price)); setLevelIds(existing.learningLevelIds); setTutorIds(existing.tutors.map((item) => item.id)); setActive(existing.active); }, [existing]);
  const save = useMutation({ mutationFn: (input: Parameters<typeof api.createPrivateTutoringService>[0]) => existing ? api.updatePrivateTutoringService(existing.id, input) : api.createPrivateTutoringService(input), onSuccess: () => { void client.invalidateQueries({ queryKey: ["private-tutoring-admin-services", organizationId] }); router.back(); } });
  if (!profile) return null; if (membership?.role !== "STAFF_ADMIN") return <Redirect href="/home" />;
  const toggle = (id: string, selected: string[], setSelected: (value: string[]) => void) => setSelected(selected.includes(id) ? selected.filter((item) => item !== id) : [...selected, id]);
  const submit = () => { const numeric = [Number(minAge), Number(maxAge), Number(duration), Number(price)]; if (!branchId || !name.trim() || numeric.some((item) => !Number.isFinite(item)) || Number(minAge) > Number(maxAge) || Number(duration) < 15 || Number(price) <= 0 || !levelIds.length || !tutorIds.length) return Alert.alert(t("privateTutoring.serviceRequired")); void save.mutateAsync({ branchId, name: name.trim(), description: description.trim(), minAgeMonths: Number(minAge), maxAgeMonths: Number(maxAge), durationMinutes: Number(duration), price: Number(price), learningLevelIds: levelIds, tutorIds, active }).catch((error) => Alert.alert(t("privateTutoring.saveFailed"), error instanceof Error ? error.message : t("auth.tryAgain"))); };
  const infoAction = (id: string) => t(openInfo === id ? "privateTutoring.hideInfo" : "privateTutoring.showInfo");
  const toggleInfo = (id: string) => setOpenInfo((current) => current === id ? null : id);
  return <AppScreen showBottomNavigation={false} title={t(existing ? "privateTutoring.editService" : "privateTutoring.addService")} header={<BackButton accessibilityLabel={t("common.back")} onPress={() => router.back()} />}><ScrollView contentContainerStyle={styles.content}>
    <TutoringFormField id="name" label={t("privateTutoring.serviceName")} info={t("privateTutoring.serviceNameInfo")} infoAction={infoAction("name")} expanded={openInfo === "name"} onToggle={() => toggleInfo("name")}><TextInput style={styles.input} placeholder={t("privateTutoring.serviceName")} value={name} onChangeText={setName} /></TutoringFormField>
    <TutoringFormField id="description" label={t("privateTutoring.serviceDescription")} info={t("privateTutoring.serviceDescriptionInfo")} infoAction={infoAction("description")} expanded={openInfo === "description"} onToggle={() => toggleInfo("description")}><TextInput style={[styles.input, styles.note]} multiline placeholder={t("privateTutoring.serviceDescription")} value={description} onChangeText={setDescription} /></TutoringFormField>
    <TutoringFormField id="branch" label={t("privateTutoring.branch")} info={t("privateTutoring.branchInfo")} infoAction={infoAction("branch")} expanded={openInfo === "branch"} onToggle={() => toggleInfo("branch")}><View style={styles.options}>{branches.data?.filter((item) => item.active).map((item) => <Button key={item.id} variant={branchId === item.id ? "primary" : "secondary"} onPress={() => setBranchId(item.id)}>{item.name}</Button>)}</View></TutoringFormField>
    <TutoringFormField id="min-age" label={t("privateTutoring.minAge")} info={t("privateTutoring.minAgeInfo")} infoAction={infoAction("min-age")} expanded={openInfo === "min-age"} onToggle={() => toggleInfo("min-age")}><TextInput style={styles.input} inputMode="numeric" placeholder={t("privateTutoring.minAge")} value={minAge} onChangeText={setMinAge} /></TutoringFormField>
    <TutoringFormField id="max-age" label={t("privateTutoring.maxAge")} info={t("privateTutoring.maxAgeInfo")} infoAction={infoAction("max-age")} expanded={openInfo === "max-age"} onToggle={() => toggleInfo("max-age")}><TextInput style={styles.input} inputMode="numeric" placeholder={t("privateTutoring.maxAge")} value={maxAge} onChangeText={setMaxAge} /></TutoringFormField>
    <TutoringFormField id="duration" label={t("privateTutoring.durationMinutes")} info={t("privateTutoring.durationInfo")} infoAction={infoAction("duration")} expanded={openInfo === "duration"} onToggle={() => toggleInfo("duration")}><TextInput style={styles.input} inputMode="numeric" placeholder={t("privateTutoring.durationMinutes")} value={duration} onChangeText={setDuration} /></TutoringFormField>
    <TutoringFormField id="price" label={t("privateTutoring.price")} info={t("privateTutoring.priceInfo")} infoAction={infoAction("price")} expanded={openInfo === "price"} onToggle={() => toggleInfo("price")}><TextInput style={styles.input} inputMode="decimal" placeholder={t("privateTutoring.price")} value={price} onChangeText={setPrice} /></TutoringFormField>
    <TutoringFormField id="levels" label={t("privateTutoring.learningLevels")} info={t("privateTutoring.learningLevelsInfo")} infoAction={infoAction("levels")} expanded={openInfo === "levels"} onToggle={() => toggleInfo("levels")}><View style={styles.options}>{levels.data?.filter((item) => item.active && item.source === "TENANT").map((item) => <Button key={item.id} variant={levelIds.includes(item.id) ? "primary" : "secondary"} onPress={() => toggle(item.id, levelIds, setLevelIds)}>{item.name}</Button>)}</View></TutoringFormField>
    <TutoringFormField id="tutors" label={t("privateTutoring.tutorSelection")} info={t("privateTutoring.tutorSelectionInfo")} infoAction={infoAction("tutors")} expanded={openInfo === "tutors"} onToggle={() => toggleInfo("tutors")}><View style={styles.options}>{tutors.data?.filter((item) => item.active).map((item) => <Button key={item.id} variant={tutorIds.includes(item.id) ? "primary" : "secondary"} onPress={() => toggle(item.id, tutorIds, setTutorIds)}>{item.displayName}</Button>)}</View></TutoringFormField>
    <TutoringFormField id="active" label={t("privateTutoring.status")} info={t("privateTutoring.activeInfo")} infoAction={infoAction("active")} expanded={openInfo === "active"} onToggle={() => toggleInfo("active")}><Button variant={active ? "primary" : "secondary"} onPress={() => setActive((value) => !value)}>{active ? t("privateTutoring.active") : t("privateTutoring.inactive")}</Button></TutoringFormField>
    <Button loading={save.isPending} onPress={submit}>{t("common.save")}</Button>
  </ScrollView></AppScreen>;
}

type TutoringFormFieldProps = { id: string; label: string; info: string; infoAction: string; expanded: boolean; onToggle: () => void; children: ReactNode };

function TutoringFormField({ id, label, info, infoAction, expanded, onToggle, children }: TutoringFormFieldProps) {
  return <View style={styles.field}><View style={styles.fieldHeader}><AppText variant="label">{label}</AppText><Pressable accessibilityRole="button" accessibilityLabel={`${infoAction}: ${label}`} accessibilityState={{ expanded }} onPress={onToggle} style={({ pressed }) => [styles.infoToggle, pressed && styles.pressed]}><AppText variant="caption" tone="muted">ⓘ {infoAction}</AppText></Pressable></View>{expanded && <View nativeID={`${id}-info`} style={styles.info}><AppText variant="caption" tone="muted">{info}</AppText></View>}{children}</View>;
}

const styles = StyleSheet.create({ content: { gap: spacing.md }, field: { gap: spacing.xs }, fieldHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: spacing.sm }, info: { padding: spacing.sm, borderRadius: 12, backgroundColor: colors.surfaceTint }, infoToggle: { paddingVertical: spacing.xs, paddingHorizontal: spacing.sm }, pressed: { opacity: 0.7 }, options: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm }, input: { minHeight: 48, paddingHorizontal: spacing.sm, borderWidth: 1, borderColor: colors.border, borderRadius: 12, backgroundColor: colors.surface }, note: { minHeight: 96, paddingVertical: spacing.sm, textAlignVertical: "top" } });
