package com.daycare.api.persistence

import com.daycare.api.domain.BookingStatus
import com.daycare.api.domain.CapacityReservationStatus
import jakarta.persistence.LockModeType
import org.springframework.data.jpa.repository.JpaRepository
import org.springframework.data.jpa.repository.Lock
import java.time.LocalDate
import java.util.UUID

interface ServicePlanRepository : JpaRepository<ServicePlan, UUID> { fun findAllByOrganizationIdAndActiveTrue(organizationId: UUID): List<ServicePlan>; @Lock(LockModeType.PESSIMISTIC_WRITE) fun findWithLockById(id: UUID): ServicePlan? }
interface InvoiceRepository : JpaRepository<Invoice, UUID> { fun findAllByOrganizationIdOrderByCreatedAtDesc(organizationId: UUID): List<Invoice>; fun findAllByOrganizationIdAndPayerUserIdOrderByCreatedAtDesc(organizationId: UUID, payerUserId: UUID): List<Invoice>; fun findAllByOrganizationIdAndStatusInAndDueDateBefore(organizationId: UUID, statuses: Collection<com.daycare.api.domain.InvoiceStatus>, dueDate: LocalDate): List<Invoice> }
interface PaymentProofRepository : JpaRepository<PaymentProof, UUID> { fun findByInvoiceId(invoiceId: UUID): PaymentProof? }
interface ServiceEntitlementRepository : JpaRepository<ServiceEntitlement, UUID> { fun findAllByInvoiceId(invoiceId: UUID): List<ServiceEntitlement>; fun findAllByOrganizationId(organizationId: UUID): List<ServiceEntitlement>; fun findAllByOrganizationIdAndOwnerUserId(organizationId: UUID, ownerUserId: UUID): List<ServiceEntitlement>; fun findAllByOrganizationIdAndChildId(organizationId: UUID, childId: UUID): List<ServiceEntitlement> }
interface BookingRepository : JpaRepository<Booking, UUID> { fun findAllByInvoiceId(invoiceId: UUID): List<Booking>; fun findAllByOrganizationIdOrderByBookingDateDesc(organizationId: UUID): List<Booking>; fun findAllByOrganizationIdAndStatusOrderByBookingDateAsc(organizationId: UUID, status: BookingStatus): List<Booking>; fun findByOrganizationIdAndChildIdAndBookingDateAndStatus(organizationId: UUID, childId: UUID, bookingDate: LocalDate, status: BookingStatus): Booking?; fun existsByOrganizationIdAndChildIdAndBookingDateAndStatusIn(organizationId: UUID, childId: UUID, bookingDate: LocalDate, statuses: Collection<BookingStatus>): Boolean }
interface BranchCapacitySettingRepository : JpaRepository<BranchCapacitySetting, UUID> { fun findAllByOrganizationId(organizationId: UUID): List<BranchCapacitySetting>; fun findByOrganizationIdAndBranchId(organizationId: UUID, branchId: UUID): BranchCapacitySetting? }
interface CapacityReservationRepository : JpaRepository<CapacityReservation, UUID> { fun countByOrganizationIdAndBranchIdAndCapacityDateAndStatus(organizationId: UUID, branchId: UUID, capacityDate: LocalDate, status: CapacityReservationStatus): Long; fun countByOrganizationIdAndServicePlanIdAndCapacityDateAndStatus(organizationId: UUID, servicePlanId: UUID, capacityDate: LocalDate, status: CapacityReservationStatus): Long; fun findAllByEntitlementIdIn(entitlementIds: Collection<UUID>): List<CapacityReservation>; fun findByEntitlementIdAndCapacityDate(entitlementId: UUID, capacityDate: LocalDate): CapacityReservation?; fun findAllByBookingId(bookingId: UUID): List<CapacityReservation>; fun findAllByOrganizationIdAndBranchIdAndCapacityDateGreaterThanEqualAndStatus(organizationId: UUID, branchId: UUID, capacityDate: LocalDate, status: CapacityReservationStatus): List<CapacityReservation> }
interface ServicePlanDiscountRepository : JpaRepository<ServicePlanDiscount, UUID> { fun findAllByOrganizationIdAndServicePlanIdOrderByCreatedAtDesc(organizationId: UUID, servicePlanId: UUID): List<ServicePlanDiscount>; fun findAllByOrganizationIdAndServicePlanIdAndActiveTrue(organizationId: UUID, servicePlanId: UUID): List<ServicePlanDiscount> }
interface ServicePlanDiscountRedemptionRepository : JpaRepository<ServicePlanDiscountRedemption, UUID> { fun countByDiscountId(discountId: UUID): Long; fun deleteAllByInvoiceId(invoiceId: UUID) }
interface ServicePlanTemplateRepository : JpaRepository<ServicePlanTemplate, UUID> { fun findAllByOrganizationIdOrderByNameAsc(organizationId: UUID): List<ServicePlanTemplate> }
